### ISSUE TITLE
Focus problem

### ISSUE THREAD

**Issue by brkcnaka** [byteburgers/react-native-autocomplete-input#338]
The version I was currently using in my project was v5.4.0. With the last update, I switched to v5.5.5. However, in this version, I could not focus on the input I rendered with renderTextInput. I've only tried it on iOS, I don't know what the situation is on Android.

I fixed the problem by downgrading back to v5.4.0.

**Comment by shrouxm** [comment]
we are also experiencing this, any time the `renderTextInput` prop changes focus is lost, which can be awkward to work around if there's a reason the text input style may change while the user is editing the text (e.g. form validation).

**Comment by mrlaessig** [comment]
This should be fixed with in [v5.5.6](https://github.com/byteburgers/react-native-autocomplete-input/releases/tag/v5.5.6)

**Comment by titanve** [comment]
> This should be fixed with in [v5.5.6](https://github.com/byteburgers/react-native-autocomplete-input/releases/tag/v5.5.6)

Hi @mrlaessig 
it is still happening to me, just upgraded to ver 5.5.6 and the textinput looses focus whenever I type something.
